
grammar_tests = {
    "level_A1": [
        {"question": "Как правильно составить повествовательное предложение: 'She ____ to the store.'?",
         "options": ["go", "goes", "going"],
         "correct": "goes"},
        {"question": "Как правильно составить вопросительное предложение: '____ you like pizza?'?",
         "options": ["Do", "Does", "Are"],
         "correct": "Do"},
        {"question": "Как правильно составить повествовательное предложение: 'They ____ to the park.'?",
         "options": ["go", "goes", "are going"],
         "correct": "go"},
        {"question": "Как правильно составить вопросительное предложение: '____ he live in London?'?",
         "options": ["Do", "Does", "Is"],
         "correct": "Does"},
        {"question": "Как правильно составить повествовательное предложение: 'I ____ a book.'?",
         "options": ["read", "reads", "am reading"],
         "correct": "read"},
        {"question": "Как правильно составить вопросительное предложение: '____ she like coffee?'?",
         "options": ["Do", "Does", "Is"],
         "correct": "Does"},
        {"question": "Как правильно составить повествовательное предложение: 'We ____ to the beach.'?",
         "options": ["go", "goes", "are going"],
         "correct": "go"},
        {"question": "Как правильно составить вопросительное предложение: '____ they study English?'?",
         "options": ["Do", "Does", "Are"],
         "correct": "Do"},
        {"question": "Как правильно составить повествовательное предложение: 'He ____ a doctor.'?",
         "options": ["is", "are", "am"],
         "correct": "is"},
        {"question": "Как правильно составить вопросительное предложение: '____ you have a pet?'?",
         "options": ["Do", "Does", "Are"],
         "correct": "Do"}
    ],
 
    "level_A2": [
        {"question": "Какое время используется в предложении: 'She goes to school every day.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Present Simple"},
        {"question": "Какое время используется в предложении: 'I went to the park yesterday.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Past Simple"},
        {"question": "Какое время используется в предложении: 'They will visit us next week.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Future Simple"},
        {"question": "Какое время используется в предложении: 'He plays football every weekend.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Present Simple"},
        {"question": "Какое время используется в предложении: 'She studied hard for the exam.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Past Simple"},
        {"question": "Какое время используется в предложении: 'We will meet at the café tomorrow.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Future Simple"},
        {"question": "Какое время используется в предложении: 'They live in a big house.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Present Simple"},
        {"question": "Какое время используется в предложении: 'He called you last night.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Past Simple"},
        {"question": "Какое время используется в предложении: 'She will travel to Spain next summer.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Future Simple"},
        {"question": "Какое время используется в предложении: 'I usually wake up at 7 AM.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Present Simple"}
    ],
       
       
    "level_B1": [
        {"question": "Какое время используется в предложении: 'I will call you later.'?",
         "options": ["Present Simple", "Future Simple", "Going to Future"],
         "correct": "Future Simple"},
        {"question": "Какое время используется в предложении: 'She is going to visit her parents next weekend.'?",
         "options": ["Present Simple", "Future Simple", "Going to Future"],
         "correct": "Going to Future"},
        {"question": "Какое время используется в предложении: 'They will be arriving soon.'?",
         "options": ["Present Simple", "Future Simple", "Future Continuous"],
         "correct": "Future Continuous"},
        {"question": "Какое время используется в предложении: 'I am going to study harder this semester.'?",
         "options": ["Present Simple", "Future Simple", "Going to Future"],
         "correct": "Going to Future"},
        {"question": "Какое время используется в предложении: 'We will have finished the project by next month.'?",
         "options": ["Present Simple", "Future Simple", "Future Perfect"],
         "correct": "Future Perfect"},
        {"question": "Какое время используется в предложении: 'He will be working from home tomorrow.'?",
         "options": ["Present Simple", "Future Simple", "Future Continuous"],
         "correct": "Future Continuous"},
        {"question": "Какое время используется в предложении: 'She is going to start a new job next month.'?",
         "options": ["Present Simple", "Future Simple", "Going to Future"],
         "correct": "Going to Future"},
        {"question": "Какое время используется в предложении: 'They will be traveling to Europe next summer.'?",
         "options": ["Present Simple", "Future Simple", "Future Continuous"],
         "correct": "Future Continuous"},
        {"question": "Какое время используется в предложении: 'I will call you when I arrive.'?",
         "options": ["Present Simple", "Future Simple", "Going to Future"],
         "correct": "Future Simple"},
        {"question": "Какое время используется в предложении: 'She is going to prepare dinner tonight.'?",
         "options": ["Present Simple", "Future Simple", "Going to Future"],
         "correct": "Going to Future"}
    ],
    
    "level_B2": [
        {"question": "Какое слово является причастием настоящего времени (Present Participle) в предложении: 'She is reading a book.'?",
         "options": ["She", "is", "reading"],
         "correct": "reading"},
        {"question": "Какое слово является причастием прошедшего времени (Past Participle) в предложении: 'The car was stolen last night.'?",
         "options": ["The", "car", "stolen"],
         "correct": "stolen"},
        {"question": "Какое слово является причастием настоящего времени (Present Participle) в предложении: 'They are playing football.'?",
         "options": ["They", "are", "playing"],
         "correct": "playing"},
        {"question": "Какое слово является причастием прошедшего времени (Past Participle) в предложении: 'He has finished his homework.'?",
         "options": ["He", "has", "finished"],
         "correct": "finished"},
        {"question": "Какое слово является причастием настоящего времени (Present Participle) в предложении: 'She is singing in the shower.'?",
         "options": ["She", "is", "singing"],
         "correct": "singing"},
        {"question": "Какое слово является причастием прошедшего времени (Past Participle) в предложении: 'The cake was baked by my mom.'?",
         "options": ["The", "cake", "baked"],
         "correct": "baked"},
        {"question": "Какое слово является причастием настоящего времени (Present Participle) в предложении: 'They are running in the park.'?",
         "options": ["They", "are", "running"],
         "correct": "running"},
        {"question": "Какое слово является причастием прошедшего времени (Past Participle) в предложении: 'The letter was written by hand.'?",
         "options": ["The", "letter", "written"],
         "correct": "written"},
        {"question": "Какое слово является причастием настоящего времени (Present Participle) в предложении: 'He is working on a new project.'?",
         "options": ["He", "is", "working"],
         "correct": "working"},
        {"question": "Какое слово является причастием прошедшего времени (Past Participle) в предложении: 'The movie has been watched by many people.'?",
         "options": ["The", "movie", "watched"],
         "correct": "watched"}
    ],
    
    "level_C1": [
        {"question": "Как правильно перевести предложение 'The book was written by her.' на русский язык?",
         "options": ["Она написала книгу.", "Книга была написана ею.", "Она пишет книгу."],
         "correct": "Книга была написана ею."},
        {"question": "Какое предложение в пассивном залоге: 'The cake is being baked.'?",
         "options": ["Торт печется.", "Они пекут торт.", "Торт был испечен."],
         "correct": "Торт печется."},
        {"question": "Как правильно перевести предложение 'The car was repaired yesterday.' на русский язык?",
         "options": ["Машина была починена вчера.", "Они починили машину вчера.", "Машина чинится."],
         "correct": "Машина была починена вчера."},
        {"question": "Какое предложение в пассивном залоге: 'The letter will be sent tomorrow.'?",
         "options": ["Письмо будет отправлено завтра.", "Они отправят письмо завтра.", "Письмо отправляется."],
         "correct": "Письмо будет отправлено завтра."},
        {"question": "Как правильно перевести предложение 'The door is being opened.' на русский язык?",
         "options": ["Дверь открывается.", "Они открывают дверь.", "Дверь была открыта."],
         "correct": "Дверь открывается."},
        {"question": "Какое предложение в пассивном залоге: 'The homework was done by the students.'?",
         "options": ["Домашняя работа была сделана студентами.", "Студенты сделали домашнюю работу.", "Домашняя работа делается."],
         "correct": "Домашняя работа была сделана студентами."},
        {"question": "Как правильно перевести предложение 'The meeting is being held in the conference room.' на русский язык?",
         "options": ["Встреча проводится в конференц-зале.", "Они проводят встречу в конференц-зале.", "Встреча была проведена в конференц-зале."],
         "correct": "Встреча проводится в конференц-зале."},
        {"question": "Какое предложение в пассивном залоге: 'The project will be completed by next week.'?",
         "options": ["Проект будет завершен к следующей неделе.", "Они завершат проект к следующей неделе.", "Проект завершается."],
         "correct": "Проект будет завершен к следующей неделе."},
        {"question": "Как правильно перевести предложение 'The window was broken by the storm.' на русский язык?",
         "options": ["Окно было разбито бурей.", "Буря разбила окно.", "Окно разбивается."],
         "correct": "Окно было разбито бурей."},
        {"question": "Какое предложение в пассивном залоге: 'The report is being reviewed by the manager.'?",
         "options": ["Отчет рассматривается менеджером.", "Менеджер рассматривает отчет.", "Отчет был рассмотрен менеджером."],
         "correct": "Отчет рассматривается менеджером."}
    ],
    
    
    "level_C2": [
        {"question": "Какое время используется в предложении: 'She said she would call me later.'?",
         "options": ["Present Simple", "Past Simple", "Future Simple"],
         "correct": "Past Simple"},
        {"question": "Какое время используется в предложении: 'He told me he had finished his homework.'?",
         "options": ["Present Perfect", "Past Perfect", "Future Perfect"],
         "correct": "Past Perfect"},
        {"question": "Какое время используется в предложении: 'I will tell her when I see her.'?",
         "options": ["Present Simple", "Future Simple", "Present Continuous"],
         "correct": "Future Simple"},
        {"question": "Какое время используется в предложении: 'She said she was going to the store.'?",
         "options": ["Past Simple", "Past Continuous", "Past Perfect"],
         "correct": "Past Continuous"},
        {"question": "Какое время используется в предложении: 'He will have finished his work by tomorrow.'?",
         "options": ["Future Simple", "Future Perfect", "Present Perfect"],
         "correct": "Future Perfect"},
        {"question": "Какое время используется в предложении: 'She said she would be happy to help.'?",
         "options": ["Past Simple", "Future Simple", "Past Perfect"],
         "correct": "Past Simple"},
        {"question": "Какое время используется в предложении: 'I will let you know when I have finished.'?",
         "options": ["Future Simple", "Future Perfect", "Present Perfect"],
         "correct": "Future Simple"},
        {"question": "Какое время используется в предложении: 'He told me he would call me back.'?",
         "options": ["Past Simple", "Future Simple", "Past Perfect"],
         "correct": "Past Simple"},
        {"question": "Какое время используется в предложении: 'She said she had been waiting for an hour.'?",
         "options": ["Past Perfect", "Past Continuous", "Past Perfect Continuous"],
         "correct": "Past Perfect Continuous"},
        {"question": "Какое время используется в предложении: 'I will inform you when I receive the details.'?",
         "options": ["Future Simple", "Present Simple", "Future Perfect"],
         "correct": "Future Simple"}
    ]
}