
word_tests = {
    "level_A": [
        {"question": "What is 'computer' in Russian?", "options": ["копировать", "компьютер", "папкат"], "correct": "компьютер"},
        {"question": "What is 'internet' in Russian?", "options": ["интернет", "программное обеспечение", "скачивать"], "correct": "интернет"},
        {"question": "What is 'email' in Russian?", "options": ["телефон", "браузер", "электронная почта"], "correct": "электронная почта"},
        {"question": "What is 'mouse' in Russian?", "options": ["мышь", "папка", "удалять"], "correct": "мышь"},
        {"question": "What is 'software' in Russian?", "options": ["программное обеспечение", "загружать", "аппаратное обеспечение"], "correct": "программное обеспечение"},
        {"question": "What is 'keyboard' in Russian?", "options": ["ноутбук", "клавиатура", "приложение"], "correct": "клавиатура"},
        {"question": "What is 'phone' in Russian?", "options": ["компьютер", "телефон", "мышь"], "correct": "телефон"},
        {"question": "What is 'browser' in Russian?", "options": ["браузер", "аппаратное обеспечение", "копировать"], "correct": "браузер"},
        {"question": "What is 'website' in Russian?", "options": ["клавиатура", "веб-сайт", "приложение"], "correct": "веб-сайт"},
        {"question": "What is 'hardware' in Russian?", "options": ["файл", "клавиатура", "аппаратное обеспечение"], "correct": "аппаратное обеспечение"},
        {"question": "What is 'screen' in Russian?", "options": ["экран", "электронная почта", "загружать"], "correct": "экран"},
        {"question": "What is 'app' in Russian?", "options": ["веб-сайт", "интернет", "приложение"], "correct": "приложение"},
        {"question": "What is 'laptop' in Russian?", "options": ["компьютер", "ноутбук", "аппаратное обеспечение"], "correct": "ноутбук"},
        {"question": "What is 'upload' in Russian?", "options": ["программное обеспечение", "загружать", "телефон"], "correct": "загружать"},
        {"question": "What is 'file' in Russian?", "options": ["папка", "удалять", "файл"], "correct": "файл"},
        {"question": "What is 'save' in Russian?", "options": ["интернет", "браузер", "сохранять"], "correct": "сохранять"},
        {"question": "What is 'download' in Russian?", "options": ["скачивать", "копировать", "мышь"], "correct": "скачивать"},
        {"question": "What is 'folder' in Russian?", "options": ["ноутбук", "клавиатура", "кпапка"], "correct": "папка"},
        {"question": "What is 'delete' in Russian?", "options": ["загружать", "удалять", "электронная почта"], "correct": "удалять"},
        {"question": "What is 'copy' in Russian?", "options": ["копировать", "скачивать", "веб-сайт"], "correct": "копировать"}
    ],
    
    "level_A1": [
       {"question": "What is 'computer' in Russian?", "options": ["копировать", "компьютер", "папкат"], "correct": "компьютер"},
        {"question": "What is 'internet' in Russian?", "options": ["интернет", "программное обеспечение", "скачивать"], "correct": "интернет"},
        {"question": "What is 'email' in Russian?", "options": ["телефон", "браузер", "электронная почта"], "correct": "электронная почта"},
        {"question": "What is 'mouse' in Russian?", "options": ["мышь", "папка", "удалять"], "correct": "мышь"},
        {"question": "What is 'software' in Russian?", "options": ["программное обеспечение", "загружать", "аппаратное обеспечение"], "correct": "программное обеспечение"},
        {"question": "What is 'keyboard' in Russian?", "options": ["ноутбук", "клавиатура", "приложение"], "correct": "клавиатура"},
        {"question": "What is 'phone' in Russian?", "options": ["компьютер", "телефон", "мышь"], "correct": "телефон"},
        {"question": "What is 'browser' in Russian?", "options": ["браузер", "аппаратное обеспечение", "копировать"], "correct": "браузер"},
        {"question": "What is 'website' in Russian?", "options": ["клавиатура", "веб-сайт", "приложение"], "correct": "веб-сайт"},
        {"question": "What is 'hardware' in Russian?", "options": ["файл", "клавиатура", "аппаратное обеспечение"], "correct": "аппаратное обеспечение"},
        {"question": "What is 'screen' in Russian?", "options": ["экран", "электронная почта", "загружать"], "correct": "экран"},
        {"question": "What is 'app' in Russian?", "options": ["веб-сайт", "интернет", "приложение"], "correct": "приложение"},
        {"question": "What is 'laptop' in Russian?", "options": ["компьютер", "ноутбук", "аппаратное обеспечение"], "correct": "ноутбук"},
        {"question": "What is 'upload' in Russian?", "options": ["программное обеспечение", "загружать", "телефон"], "correct": "загружать"},
        {"question": "What is 'file' in Russian?", "options": ["папка", "удалять", "файл"], "correct": "файл"},
        {"question": "What is 'save' in Russian?", "options": ["интернет", "браузер", "сохранять"], "correct": "сохранять"},
        {"question": "What is 'download' in Russian?", "options": ["скачивать", "копировать", "мышь"], "correct": "скачивать"},
        {"question": "What is 'folder' in Russian?", "options": ["ноутбук", "клавиатура", "кпапка"], "correct": "папка"},
        {"question": "What is 'delete' in Russian?", "options": ["загружать", "удалять", "электронная почта"], "correct": "удалять"},
        {"question": "What is 'copy' in Russian?", "options": ["копировать", "скачивать", "веб-сайт"], "correct": "копировать"}
    ],
    
    "level_A2": [
       {"question": "What is 'paste' in Russian?", "options": ["хранилище", "вставлять", "ссылка"], "correct": "вставлять"},
        {"question": "What is 'login' in Russian?", "options": ["выход", "япользователь", "вход"], "correct": "вход"},
        {"question": "What is 'scan' in Russian?", "options": ["аккаунт", "сканировать", "скачивать"], "correct": "сканировать"},
        {"question": "What is 'printer' in Russian?", "options": ["принтер", "вставлять", "аппаратное обеспечение"], "correct": "принтер"},
        {"question": "What is 'desktop' in Russian?", "options": ["рабочий стол", "печатать", "пользователь"], "correct": "рабочий стол"},
        {"question": "What is 'password' in Russian?", "options": ["вход", "пароль", "приложение"], "correct": "пароль"},
        {"question": "What is 'double-click' in Russian?", "options": ["выход", "кликать", "двойной клик"], "correct": "двойной клик"},
        {"question": "What is 'window' in Russian?", "options": ["окно", "иконка", "хранилище"], "correct": "окно"},
        {"question": "What is 'click' in Russian?", "options": ["сканировать", "кликать", "вход"], "correct": "кликать"},
        {"question": "What is 'print' in Russian?", "options": [" печатать", "приложение", "иконка"], "correct": "печатать"},
        {"question": "What is 'user' in Russian?", "options": ["кликать", "пользователь", "ссылка"], "correct": "пользователь"},
        {"question": "What is 'logout' in Russian?", "options": ["выход", "сканировать", "двойной клик"], "correct": "выход"},
        {"question": "What is 'memory' in Russian?", "options": ["ссылка", "память", "печатать"], "correct": "память"},
        {"question": "What is 'Wi-Fi (Wireless Fidelity)' in Russian?", "options": ["вставлять", "технология беспроводной локальной сети", "аппаратное обеспечение"], "correct": "технология беспроводной локальной сети"},
        {"question": "What is 'icon' in Russian?", "options": ["хранилище", "иконка", "окно"], "correct": "иконка"},
        {"question": "What is 'link' in Russian?", "options": ["аккаунт", "выход", "ссылка"], "correct": "ссылка"},
        {"question": "What is 'search' in Russian?", "options": ["пользователь", "скачивать", "поиск"], "correct": "поиск"},
        {"question": "What is 'account' in Russian?", "options": ["кликать", "аккаунт", "двойной клик"], "correct": "аккаунт"},
        {"question": "What is 'cable' in Russian?", "options": ["кабель", "приложение", "окно"], "correct": "кабель"},
        {"question": "What is 'storage' in Russian?", "options": ["сканировать", "хранилище", "аппаратное обеспечение"], "correct": "хранилище"}
    ],
    "level_B": [
        {"question": "What is 'database' in Russian?", "options": ["дешифрование", "хранилище", "база данных"], "correct": "база данных"},
        {"question": "What is 'IP address (Internet Protocol)' in Russian?", "options": ["уникальный числовой идентификатор устройства", "виртуальная частная сеть", "унифицированный указатель ресурса"], "correct": "уникальный числовой идентификатор устройства"},
        {"question": "What is 'network' in Russian?", "options": ["межсетевой экран", "ссылка", "модем"], "correct": "сеть"},
        {"question": "What is 'router' in Russian?", "options": ["унифицированный указатель ресурса", " маршрутизатор", "база данных"], "correct": " маршрутизатор"},
        {"question": "What is 'server' in Russian?", "options": ["сервер", "маршрутизатор", "база данных"], "correct": "межсетевой экран"},
        {"question": "What is 'firewall' in Russian?", "options": ["межсетевой экран", "хранилище", "сеть"], "correct": "межсетевой экран"},
        {"question": "What is 'URL (Uniform Resource Locator)' in Russian?", "options": ["унифицированный указатель ресурса", "виртуальная частная сеть", "ссылка"], "correct": "унифицированный указатель ресурса"},
        {"question": "What is 'encryption' in Russian?", "options": ["шифрование", "база данных", "межсетевой экран"], "correct": "шифрование"},
        {"question": "What is 'domain' in Russian?", "options": ["база данных", "межсетевой экран", "домен"], "correct": "домен"},
        {"question": "What is 'DNS (Domain Name System)' in Russian?", "options": ["сервер", "уникальный числовой идентификатор устройства", "система доменных имён"], "correct": "система доменных имён"},
        {"question": "What is 'HTTPS (HyperText Transfer Protocol Secure)' in Russian?", "options": [" расширение протокола HTTP", "ссылка", "протокол для передачи файлов между клиентом и сервером"], "correct": " расширение протокола HTTP"},
        {"question": "What is 'modem' in Russian?", "options": ["сеть", "модем", "дешифрование"], "correct": "модем"},
        {"question": "What is 'host' in Russian?", "options": ["модем", "хост", "межсетевой экран"], "correct": "хост"},
        {"question": "What is 'bandwidth' in Russian?", "options": ["пропускная способность", "маршрутизатор", "база данных"], "correct": "пропускная способность"},
        {"question": "What is 'protocol' in Russian?", "options": ["модем", "межсетевой экран", " протокол"], "correct": " протокол"},
        {"question": "What is 'FTP (File Transfer Protocol)' in Russian?", "options": ["унифицированный указатель ресурса", "протокол для передачи файлов между клиентом и сервером", " расширение протокола HTTP"], "correct": "протокол для передачи файлов между клиентом и сервером"},
        {"question": "What is 'proxy' in Russian?", "options": ["промежуточный сервер между пользователем интернета и серверами", "ссылка", "база данных"], "correct": "промежуточный сервер между пользователем интернета и серверами"},
        {"question": "What is 'VPN (Virtual Private Network)' in Russian?", "options": ["межсетевой экран", "протокол для передачи файлов между клиентом и сервером", "виртуальная частная сеть"], "correct": "виртуальная частная сеть"},
        {"question": "What is 'HTTP (HyperText Transfer Protocol)' in Russian?", "options": ["унифицированный указатель ресурса", "уникальный числовой идентификатор устройства", "протокол передачи данных в интернете"], "correct": "протокол передачи данных в интернете"},
        {"question": "What is 'decryption' in Russian?", "options": ["унифицированный указатель ресурса", "шифрование", "дешифрование"], "correct": "дешифрование"}
    ],
    "level_B1": [
        {"question": "What is 'database' in Russian?", "options": ["дешифрование", "хранилище", "база данных"], "correct": "база данных"},
        {"question": "What is 'IP address (Internet Protocol)' in Russian?", "options": ["уникальный числовой идентификатор устройства", "виртуальная частная сеть", "унифицированный указатель ресурса"], "correct": "уникальный числовой идентификатор устройства"},
        {"question": "What is 'network' in Russian?", "options": ["межсетевой экран", "ссылка", "модем"], "correct": "сеть"},
        {"question": "What is 'router' in Russian?", "options": ["унифицированный указатель ресурса", " маршрутизатор", "база данных"], "correct": " маршрутизатор"},
        {"question": "What is 'server' in Russian?", "options": ["сервер", "маршрутизатор", "база данных"], "correct": "межсетевой экран"},
        {"question": "What is 'firewall' in Russian?", "options": ["межсетевой экран", "хранилище", "сеть"], "correct": "межсетевой экран"},
        {"question": "What is 'URL (Uniform Resource Locator)' in Russian?", "options": ["унифицированный указатель ресурса", "виртуальная частная сеть", "ссылка"], "correct": "унифицированный указатель ресурса"},
        {"question": "What is 'encryption' in Russian?", "options": ["шифрование", "база данных", "межсетевой экран"], "correct": "шифрование"},
        {"question": "What is 'domain' in Russian?", "options": ["база данных", "межсетевой экран", "домен"], "correct": "домен"},
        {"question": "What is 'DNS (Domain Name System)' in Russian?", "options": ["сервер", "уникальный числовой идентификатор устройства", "система доменных имён"], "correct": "система доменных имён"},
        {"question": "What is 'HTTPS (HyperText Transfer Protocol Secure)' in Russian?", "options": [" расширение протокола HTTP", "ссылка", "протокол для передачи файлов между клиентом и сервером"], "correct": " расширение протокола HTTP"},
        {"question": "What is 'modem' in Russian?", "options": ["сеть", "модем", "дешифрование"], "correct": "модем"},
        {"question": "What is 'host' in Russian?", "options": ["модем", "хост", "межсетевой экран"], "correct": "хост"},
        {"question": "What is 'bandwidth' in Russian?", "options": ["пропускная способность", "маршрутизатор", "база данных"], "correct": "пропускная способность"},
        {"question": "What is 'protocol' in Russian?", "options": ["модем", "межсетевой экран", " протокол"], "correct": " протокол"},
        {"question": "What is 'FTP (File Transfer Protocol)' in Russian?", "options": ["унифицированный указатель ресурса", "протокол для передачи файлов между клиентом и сервером", " расширение протокола HTTP"], "correct": "протокол для передачи файлов между клиентом и сервером"},
        {"question": "What is 'proxy' in Russian?", "options": ["промежуточный сервер между пользователем интернета и серверами", "ссылка", "база данных"], "correct": "промежуточный сервер между пользователем интернета и серверами"},
        {"question": "What is 'VPN (Virtual Private Network)' in Russian?", "options": ["межсетевой экран", "протокол для передачи файлов между клиентом и сервером", "виртуальная частная сеть"], "correct": "виртуальная частная сеть"},
        {"question": "What is 'HTTP (HyperText Transfer Protocol)' in Russian?", "options": ["унифицированный указатель ресурса", "уникальный числовой идентификатор устройства", "протокол передачи данных в интернете"], "correct": "протокол передачи данных в интернете"},
        {"question": "What is 'decryption' in Russian?", "options": ["унифицированный указатель ресурса", "шифрование", "дешифрование"], "correct": "дешифрование"}
    ],
    
    "level_B2": [
        {"question": "What is 'restore' in Russian?", "options": ["модем", "восстановление", "межсетевой экран"], "correct": "восстановление"},
        {"question": "What is 'algorithm' in Russian?", "options": ["алгоритм", "фреймворк", "маршрутизатор"], "correct": "алгоритм"},
        {"question": "What is 'patch' in Russian?", "options": ["виртуальный", "небольшой текстовый файл", "фрагмент кода"], "correct": "фрагмент кода"},
        {"question": "What is 'framework' in Russian?", "options": ["аутентификация", "фреймворк", "хранилище"], "correct": "фреймворк"},
        {"question": "What is 'interface' in Russian?", "options": ["кластер", "дешифрование", "интерфейс"], "correct": "интерфейс"},
        {"question": "What is 'balance' in Russian?", "options": ["кэш", "баланс", "фрагмент кода"], "correct": "баланс"},
        {"question": "What is 'session' in Russian?", "options": ["кликать", "определённый промежуток времени", "небольшой текстовый файл"], "correct": "определённый промежуток времени"},
        {"question": "What is 'cookie' in Russian?", "options": ["хость", "небольшой текстовый файл", "резервное копирование"], "correct": "небольшой текстовый файл"},
        {"question": "What is 'load' in Russian?", "options": ["нагрузка", "дешифрование", "межсетевой экран"], "correct": "нагрузка"},
        {"question": "What is 'backup' in Russian?", "options": ["резервное копирование", "хранилище", "алгоритм"], "correct": "резервное копирование"},
        {"question": "What is 'update' in Russian?", "options": ["модем", " обновление", "кликать"], "correct": " обновление"},
        {"question": "What is 'driver' in Russian?", "options": ["хост", "драйвер", "резервное копирование"], "correct": "драйвер"},
        {"question": "What is 'API (Application Programming Interface)' in Russian?", "options": ["база данныхь", "набор правил и протоколов, который позволяет различным программным приложениям взаимодействовать друг с другом", "восстановление"], "correct": "набор правил и протоколов, который позволяет различным программным приложениям взаимодействовать друг с другом"},
        {"question": "What is 'administrator' in Russian?", "options": ["аутентификация", "администратор", "алгоритм"], "correct": "администратор"},
        {"question": "What is 'cluster' in Russian?", "options": ["фрагмент кода", "кластер", "небольшой текстовый файл"], "correct": "кластер"},
        {"question": "What is 'library' in Russian?", "options": ["библиотека", "резервное копирование", "маршрутизатор"], "correct": "библиотека"},
        {"question": "What is 'authentication' in Russian?", "options": ["фреймворк", "алгоритм", " аутентификация"], "correct": " аутентификация"},
        {"question": "What is 'cache' in Russian?", "options": ["восстановление", "кэш", "дешифрование"], "correct": "кэш"},
        {"question": "What is 'virtual' in Russian?", "options": ["кластер", "виртуальный", "небольшой текстовый файл"], "correct": "виртуальный"},
        {"question": "What is 'role' in Russian?", "options": ["роль", "восстановление", "аутентификация"], "correct": "роль"}
        
    ],
    
    "level_C": [
        {"question": "What is 'cybersecurity' in Russian?", "options": ["вторжение", "кибербезопасность", "нейронная сеть"], "correct": "кибербезопасность"},
        {"question": "What is 'phishing' in Russian?", "options": ["фишинг", "вредоносное ПО", "майнинг данных"], "correct": "фишинг"},
        {"question": "What is 'intrusion' in Russian?", "options": ["криптография", "говорить", "вторжение"], "correct": "вторжение"},
        {"question": "What is 'virus' in Russian?", "options": ["вторжение", "вирус", "уязвимость"], "correct": "вирус"},
        {"question": "What is 'artificial intelligence' in Russian?", "options": ["искусственный интеллект", "судебная экспертиза", "машинное обучение"], "correct": "искусственный интеллект"},
        {"question": "What is 'penetration' in Russian?", "options": ["уязвимость", "глубокое обучение", " проникновение"], "correct": " проникновение"},
        {"question": "What is 'malware' in Russian?", "options": ["фрагмент кода", "вредоносное ПО", "нейронная сеть"], "correct": "вредоносное ПО"},
        {"question": "What is 'cryptography' in Russian?", "options": ["криптография", "машинное обучение", "вредоносное ПО"], "correct": "криптография"},
        {"question": "What is 'quantum computing' in Russian?", "options": ["судебная экспертиза", " квантовые вычисления", "фрагмент кода"], "correct": " квантовые вычисления"},
        {"question": "What is 'machine learning' in Russian?", "options": ["майнинг данных", "искусственный интеллект", " машинное обучение"], "correct": " машинное обучение"},
        {"question": "What is 'blockchain' in Russian?", "options": ["нейронная сеть", "кибербезопасностьь", "блокчейн"], "correct": "блокчейн"},
        {"question": "What is 'trojan' in Russian?", "options": ["вид вредоносного программного обеспечения", "искусственный интеллект", "вторжение"], "correct": "вид вредоносного программного обеспечения"},
        {"question": "What is 'vulnerability' in Russian?", "options": ["уязвимость", "вредоносное ПО", "аутентификация"], "correct": "уязвимость"},
        {"question": "What is 'ransomware' in Russian?", "options": ["программа-вымогатель", "дешифрование", "восстановление"], "correct": "программа-вымогатель"},
        {"question": "What is 'deep learning' in Russian?", "options": ["аутентификация", "глубокое обучение", "резервное копирование"], "correct": "глубокое обучение"},
        {"question": "What is 'neural network' in Russian?", "options": ["вид вредоносного программного обеспечения", "говорить", "нейронная сеть"], "correct": "нейронная сеть"},
        {"question": "What is 'exploit ' in Russian?", "options": ["кибербезопасность", "эксплойт", "вторжение"], "correct": "эксплойт"},
        {"question": "What is 'big data' in Russian?", "options": ["глубокое обучение", "большие данные", "искусственный интеллект"], "correct": "большие данные"},
        {"question": "What is 'data mining' in Russian?", "options": ["майнинг данных", "криптография", "вид вредоносного программного обеспечения"], "correct": "майнинг данных"},
        {"question": "What is 'forensics' in Russian?", "options": ["судебная экспертиза", "уязвимость", "машинное обучение"], "correct": "судебная экспертиза"}
    ],
    "level_C1": [
        {"question": "What is 'cybersecurity' in Russian?", "options": ["вторжение", "кибербезопасность", "нейронная сеть"], "correct": "кибербезопасность"},
        {"question": "What is 'phishing' in Russian?", "options": ["фишинг", "вредоносное ПО", "майнинг данных"], "correct": "фишинг"},
        {"question": "What is 'intrusion' in Russian?", "options": ["криптография", "говорить", "вторжение"], "correct": "вторжение"},
        {"question": "What is 'virus' in Russian?", "options": ["вторжение", "вирус", "уязвимость"], "correct": "вирус"},
        {"question": "What is 'artificial intelligence' in Russian?", "options": ["искусственный интеллект", "судебная экспертиза", "машинное обучение"], "correct": "искусственный интеллект"},
        {"question": "What is 'penetration' in Russian?", "options": ["уязвимость", "глубокое обучение", " проникновение"], "correct": " проникновение"},
        {"question": "What is 'malware' in Russian?", "options": ["фрагмент кода", "вредоносное ПО", "нейронная сеть"], "correct": "вредоносное ПО"},
        {"question": "What is 'cryptography' in Russian?", "options": ["криптография", "машинное обучение", "вредоносное ПО"], "correct": "криптография"},
        {"question": "What is 'quantum computing' in Russian?", "options": ["судебная экспертиза", " квантовые вычисления", "фрагмент кода"], "correct": " квантовые вычисления"},
        {"question": "What is 'machine learning' in Russian?", "options": ["майнинг данных", "искусственный интеллект", " машинное обучение"], "correct": " машинное обучение"},
        {"question": "What is 'blockchain' in Russian?", "options": ["нейронная сеть", "кибербезопасностьь", "блокчейн"], "correct": "блокчейн"},
        {"question": "What is 'trojan' in Russian?", "options": ["вид вредоносного программного обеспечения", "искусственный интеллект", "вторжение"], "correct": "вид вредоносного программного обеспечения"},
        {"question": "What is 'vulnerability' in Russian?", "options": ["уязвимость", "вредоносное ПО", "аутентификация"], "correct": "уязвимость"},
        {"question": "What is 'ransomware' in Russian?", "options": ["программа-вымогатель", "дешифрование", "восстановление"], "correct": "программа-вымогатель"},
        {"question": "What is 'deep learning' in Russian?", "options": ["аутентификация", "глубокое обучение", "резервное копирование"], "correct": "глубокое обучение"},
        {"question": "What is 'neural network' in Russian?", "options": ["вид вредоносного программного обеспечения", "говорить", "нейронная сеть"], "correct": "нейронная сеть"},
        {"question": "What is 'exploit ' in Russian?", "options": ["кибербезопасность", "эксплойт", "вторжение"], "correct": "эксплойт"},
        {"question": "What is 'big data' in Russian?", "options": ["глубокое обучение", "большие данные", "искусственный интеллект"], "correct": "большие данные"},
        {"question": "What is 'data mining' in Russian?", "options": ["майнинг данных", "криптография", "вид вредоносного программного обеспечения"], "correct": "майнинг данных"},
        {"question": "What is 'forensics' in Russian?", "options": ["судебная экспертиза", "уязвимость", "машинное обучение"], "correct": "судебная экспертиза"}
        ],
    
    "level_C2": [
        {"question": "What is 'pipeline' in Russian?", "options": ["дешифрование", "конвейер", "база данных"], "correct": "конвейер"},
        {"question": "What is 'ETL (Extract, transform, load)' in Russian?", "options": ["уникальный числовой идентификатор устройства", "трёхэтапный вычислительный процесс", "унифицированный указатель ресурса"], "correct": "трёхэтапный вычислительный процесс"},
        {"question": "What is 'visualization' in Russian?", "options": ["межсетевой экран", "визуализация", "модем"], "correct": "визуализация"},
        {"question": "What is 'business intelligence' in Russian?", "options": ["унифицированный указатель ресурса", " бизнес-аналитика", "база данных"], "correct": " бизнес-аналитика"},
        {"question": "What is 'OLAP (On-Line Analytical Processing)' in Russian?", "options": ["сервер", "анализ данных в реальном времени", "база данных"], "correct": "анализ данных в реальном времени"},
        {"question": "What is 'agile' in Russian?", "options": ["межсетевой экран", "хранилище", "гибкий"], "correct": "гибкий"},
        {"question": "What is 'scrum' in Russian?", "options": ["унифицированный указатель ресурса", "скрам (методика гибкого управления проектами)", "ссылка"], "correct": "скрам (методика гибкого управления проектами)"},
        {"question": "What is 'IoT (internet of things)' in Russian?", "options": ["шифрование", "интернет вещей", "межсетевой экран"], "correct": "интернет вещей"},
        {"question": "What is 'sprint' in Russian?", "options": ["база данных", "межсетевой экран", "спринт (небольшой фиксированный отрезок времени)"], "correct": "спринт (небольшой фиксированный отрезок времени)"},
        {"question": "What is 'dashboard' in Russian?", "options": ["панель управления", "уникальный числовой идентификатор устройства", "система доменных имён"], "correct": "панель управления"},
        {"question": "What is 'containerization' in Russian?", "options": [" расширение протокола HTTP", "контейнеризация", "протокол для передачи файлов между клиентом и сервером"], "correct": "контейнеризация"},
        {"question": "What is 'orchestration' in Russian?", "options": ["оркестровка", "модем", "дешифрование"], "correct": "оркестровка"},
        {"question": "What is 'edge computing' in Russian?", "options": ["модем", "вычисления на краю", "межсетевой экран"], "correct": "вычисления на краю"},
        {"question": "What is 'DevOps (Development Operations)' in Russian?", "options": ["пропускная способность", "маршрутизатор", "методология взаимодействия разработчиков"], "correct": "методология взаимодействия разработчиков"},
        {"question": "What is 'backlog' in Russian?", "options": ["бэклог (список задач, требований и функций)", "межсетевой экран", " протокол"], "correct": "бэклог (список задач, требований и функций)"},
        {"question": "What is 'kanban' in Russian?", "options": ["унифицированный указатель ресурса", "канбан ( методология для управления задачами в IT-сфере)", " расширение протокола HTTP"], "correct": "канбан ( методология для управления задачами в IT-сфере)"},
        {"question": "What is 'CI/CD (Continuous Integration, Continuous Delivery)' in Russian?", "options": ["промежуточный сервер между пользователем интернета и серверами", "непрерывная интеграция и доставка", "база данных"], "correct": "непрерывная интеграция и доставка"},
        {"question": "What is 'microservices", "options": ["микросервисы", "протокол для передачи файлов между клиентом и сервером", "виртуальная частная сеть"], "correct": "микросервисы"},
        {"question": "What is 'serverless", "options": ["унифицированный указатель ресурса", "безсерверный", "протокол передачи данных в интернете"], "correct": "безсерверный"},
        {"question": "What is 'ugmented reality' in Russian?", "options": ["унифицированный указатель ресурса", "дополненная реальность", "дешифрование"], "correct": "дополненная реальность"}
    ]
}